import esbuild from 'esbuild'
import process from 'process'
import path from 'path'
import fs from 'fs'

const runtimeDir = import.meta.dirname
const outdir = path.join(runtimeDir, 'out')

console.log(`Building to directory: ${outdir}\n`)

fs.mkdirSync(outdir, { recursive: true })
fs.copyFileSync(path.join(runtimeDir, 'panel.html'), path.join(outdir, 'panel.html'))
fs.copyFileSync(path.join(runtimeDir, 'sheet.html'), path.join(outdir, 'sheet.html'))
fs.copyFileSync(path.join(runtimeDir, 'inspector.html'), path.join(outdir, 'inspector.html'))

const prod = process.argv[2] === 'production'
const context = await esbuild.context({
  banner: { js: '// GENERATED BY ESBUILD' },
  target: 'esnext',
  entryPoints: [
    path.join(runtimeDir, 'common'),
    path.join(runtimeDir, 'sheet'),
    path.join(runtimeDir, 'panel'),
    path.join(runtimeDir, 'inspector'),
  ],
  external: ['bike/dom'],
  nodePaths: [path.join(runtimeDir, '..', 'node_modules')],
  format: 'iife',
  logLevel: 'info',
  sourcemap: prod ? 'external' : 'inline',
  outdir: outdir,
  bundle: true,
  minify: prod,
  keepNames: true,
})

if (prod) {
  await context.rebuild()
  process.exit(0)
} else {
  await context.watch()
}
