import externalGlobalPlugin from 'esbuild-plugin-external-global'
import { copyAndValidatePlugin, typecheckPlugin, installExtensionPlugin, runBuildContext } from './plugins.mjs'
import esbuild from 'esbuild'
import process from 'process'
import path from 'path'
import Ajv from 'ajv'
import fs from 'fs'

const packageRoot = path.resolve(import.meta.dirname, '..')
const projectRoot = process.cwd()

export async function build(mode, { install = false, exit = true } = {}) {
  const prod = mode === 'production'

  const themeSchema = JSON.parse(
    fs.readFileSync(path.join(packageRoot, 'schemas/theme-schema.json'), 'utf-8')
  )
  const ajv = new Ajv({ allErrors: true })
  const validateTheme = ajv.compile(themeSchema)

  const outdir = path.join(projectRoot, 'out/extensions')
  const srcDir = path.join(projectRoot, 'src')

  console.log(`Building to directory: ${outdir}\n`)

  const context = await esbuild.context({
    banner: { js: '// GENERATED BY ESBUILD' },
    logOverride: { 'empty-glob': 'silent' },
    entryPoints: [
      path.join(projectRoot, 'src/**/app/main.ts'),
      path.join(projectRoot, 'src/**/style/main.ts'),
      path.join(projectRoot, 'src/**/dom/*.ts'),
      path.join(projectRoot, 'src/**/dom/*.tsx'),
      path.join(projectRoot, 'src/**/tests/*.test.ts'),
    ],
    external: ['bike/app', 'bike/dom', 'bike/style', 'bike/components', 'react', 'react-dom'],
    plugins: [
      externalGlobalPlugin.externalGlobalPlugin({
        react: 'window.React',
        'react-dom': 'window.ReactDOM',
        'react-dom/client': 'window.ReactDOMClient',
        'react/jsx-runtime': 'window.ReactJSXRuntime',
        'bike/components': 'window.BikeComponents',
      }),
      copyAndValidatePlugin(outdir, srcDir, validateTheme, {
        manifestPattern: path.join(projectRoot, 'src/**/manifest.json'),
        themePattern: path.join(projectRoot, 'src/**/theme/*.bktheme'),
      }),
      typecheckPlugin(packageRoot, projectRoot),
      ...(install ? [installExtensionPlugin(outdir)] : []),
    ],

    format: 'iife',
    globalName: 'extensionExports',
    sourcemap: prod ? 'external' : 'inline',
    treeShaking: true,
    outdir: outdir,
    outbase: path.join(projectRoot, 'src'),
    bundle: true,
    minify: prod,
  })

  await runBuildContext(context, mode, { exit })
}
