import externalGlobalPlugin from 'esbuild-plugin-external-global'
import { copyAndValidatePlugin, typecheckPlugin, installExtensionPlugin, runBuildContext } from './plugins.mjs'
import { clean } from './clean.mjs'
import esbuild from 'esbuild'
import process from 'process'
import path from 'path'
import addFormats from 'ajv-formats'
import Ajv from 'ajv'
import fs from 'fs'

const packageRoot = path.resolve(import.meta.dirname, '..')
const projectRoot = process.cwd()

export async function build(mode, { install = false, exit = true, id } = {}) {
  const prod = mode === 'production'

  const ajv = new Ajv({ allErrors: true, validateSchema: false })
  addFormats(ajv)
  const manifestSchema = JSON.parse(
    fs.readFileSync(path.join(packageRoot, 'schemas/manifest.schema.json'), 'utf-8')
  )
  const themeSchema = JSON.parse(
    fs.readFileSync(path.join(packageRoot, 'schemas/theme-schema.json'), 'utf-8')
  )
  const validateManifest = ajv.compile(manifestSchema)
  const validateTheme = ajv.compile(themeSchema)

  const outdir = path.join(projectRoot, 'out/extensions')
  const srcDir = path.join(projectRoot, 'src')

  // Extension filter: specific id or all (**)
  const ext = id ? `${id}.bkext` : '**'

  clean(outdir)
  console.log(`Building ${id || 'all extensions'} to directory: ${outdir}\n`)

  const context = await esbuild.context({
    banner: { js: '// GENERATED BY ESBUILD' },
    logOverride: { 'empty-glob': 'silent' },
    entryPoints: [
      path.join(projectRoot, 'src/copy-and-validate'),
      path.join(projectRoot, `src/${ext}/app/main.ts`),
      path.join(projectRoot, `src/${ext}/style/main.ts`),
      path.join(projectRoot, `src/${ext}/dom/*.ts`),
      path.join(projectRoot, `src/${ext}/dom/*.tsx`),
      path.join(projectRoot, `src/${ext}/tests/*.test.ts`),
    ],
    external: ['bike/app', 'bike/dom', 'bike/style', 'bike/components', 'react', 'react-dom'],
    plugins: [
      externalGlobalPlugin.externalGlobalPlugin({
        react: 'window.React',
        'react-dom': 'window.ReactDOM',
        'react-dom/client': 'window.ReactDOMClient',
        'react/jsx-runtime': 'window.ReactJSXRuntime',
        'bike/components': 'window.BikeComponents',
      }),
      copyAndValidatePlugin(outdir, srcDir, validateManifest, validateTheme, {
        manifestPattern: path.join(projectRoot, `src/${ext}/manifest.json`),
        themePattern: path.join(projectRoot, `src/${ext}/theme/*.bktheme`),
      }),
      typecheckPlugin(packageRoot, projectRoot),
      ...(install ? [installExtensionPlugin(outdir)] : []),
    ],

    format: 'iife',
    globalName: 'extensionExports',
    sourcemap: prod ? 'external' : 'inline',
    treeShaking: true,
    outdir: outdir,
    outbase: path.join(projectRoot, 'src'),
    bundle: true,
    minify: prod,
  })

  await runBuildContext(context, mode, { exit })
}
