import { runBuildContext } from './plugins.mjs'
import esbuild from 'esbuild'
import path from 'path'
import fs from 'fs'

const packageRoot = path.resolve(import.meta.dirname, '..')

export async function buildRuntime(mode) {
  const prod = mode === 'production'
  const runtimeDir = path.join(packageRoot, 'runtime')
  const outdir = path.join(runtimeDir, 'out')

  console.log(`Building runtime to directory: ${outdir}\n`)

  fs.mkdirSync(outdir, { recursive: true })
  fs.copyFileSync(path.join(runtimeDir, 'sheet.html'), path.join(outdir, 'sheet.html'))
  fs.copyFileSync(path.join(runtimeDir, 'inspector.html'), path.join(outdir, 'inspector.html'))

  const context = await esbuild.context({
    banner: { js: '// GENERATED BY ESBUILD' },
    target: 'esnext',
    entryPoints: [
      path.join(runtimeDir, 'common'),
      path.join(runtimeDir, 'sheet'),
      path.join(runtimeDir, 'inspector'),
    ],
    external: ['bike/dom'],
    nodePaths: [path.join(packageRoot, 'node_modules')],
    format: 'iife',
    logLevel: 'info',
    sourcemap: prod ? 'external' : 'inline',
    outdir: outdir,
    bundle: true,
    minify: prod,
    keepNames: true,
  })

  await runBuildContext(context, mode)
}
